### PR TITLE
Added missing French translations + Corrections

### PR DESCRIPTION
**Pull request by NathanBnm**

### CODE REVIEW

**Comment by alcinnz** [comment]
Thanks! I'll release a new update with these new translations within a week.

Another place to look: https://github.com/alcinnz/Odysseus/tree/master/data/page-l10n , I'm sorry there aren't many good tools to specialized to help edit those files. I have put some work into trying to fix that.

**Comment by NathanBnm** [comment]
@alcinnz didn't really understand how I can contribute to the link you posted, can you explain?

**Comment by alcinnz** [comment]
Fair enough.

Copy Odysseus.messages into a file "fr", and observe it's made up of lines `{%msg`source`%}`text`{%trans%}{%endmsg%}`.

Write your translations for that text between `{%trans%}` and `{%endmsg%}`. This translation text is in minimal HTML with any text between curly braces being special. Leave them as-is in the translation.

Is that clear enough?

**Comment by NathanBnm** [comment]
Yes this is clear now. The translations are done, but it was really hard to read. Can you think of a better solution in the future?

Otherwise some of the strings to be translated made me laugh! :+1:

**Comment by alcinnz** [comment]
Just curious, which translations did you find humerous?

Off the top of my mind there's "I can't understand this website. It doesn't speak the same language I do"

**Comment by NathanBnm** [comment]
Yes, this one was funny, but there's also the fact that the navigator speaks in the first person for example.

**Pull request merged**
